// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgz5NIOFhJtp5K-nCGYf8X9tV6UO-Bb4Y',
    appId: '1:407784500827:web:8802244b4db943bd8a197e',
    messagingSenderId: '407784500827',
    projectId: 'joblistingapp-c00d6',
    authDomain: 'joblistingapp-c00d6.firebaseapp.com',
    storageBucket: 'joblistingapp-c00d6.appspot.com',
    measurementId: 'G-FN3EL8L4C4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn26xbAjLv1sGMBhfFGc0u7kEeMtdTXEI',
    appId: '1:407784500827:android:dfb77873e7c919a38a197e',
    messagingSenderId: '407784500827',
    projectId: 'joblistingapp-c00d6',
    storageBucket: 'joblistingapp-c00d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZBtbZUUBijbJnm9bkcHy7eIGIrJzzA30',
    appId: '1:407784500827:ios:18625dcaddec44158a197e',
    messagingSenderId: '407784500827',
    projectId: 'joblistingapp-c00d6',
    storageBucket: 'joblistingapp-c00d6.appspot.com',
    iosBundleId: 'com.example.joblistingAppAllview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZBtbZUUBijbJnm9bkcHy7eIGIrJzzA30',
    appId: '1:407784500827:ios:52e36ae4629a58028a197e',
    messagingSenderId: '407784500827',
    projectId: 'joblistingapp-c00d6',
    storageBucket: 'joblistingapp-c00d6.appspot.com',
    iosBundleId: 'com.example.joblistingAppAllview.RunnerTests',
  );
}
